In [1]:
import numpy as np

In [4]:
#How to declare an array
a=np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [5]:
#Dimensions of array
a.ndim

1

In [7]:
#2D array declaration
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#1D array declaring by specifing range
c = np.arange(11,21)

In [10]:
c

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
#1D array with range and difference
d = np.arange(12,31,2)

In [23]:
d

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [24]:
d.shape=(2,5)

In [25]:
d

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [36]:
#Empty array
e = np.empty([4,5],dtype=int)

In [37]:
e

array([[-1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [41]:
f=np.zeros(15)

In [42]:
f

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
g = np.ones(10)

In [47]:
g

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])